apps/teams/urls.py
from django.urls import path, include
from . import views

app_name = 'teams'

urlpatterns = [
    path('create/', views.teams_create, name='create'),
    path('auto-create/', views.teams_create_randomly, name='auto-create'),
    path('<int:id>/', views.teams_retrieve, name='retrieve'),

]

apps/tournaments/urls.py
from django.urls import path, include
from . import views
from . import stage_views

app_name = 'tournaments'

urlpatterns = [
    path('create/', views.tournament_create, name='create'),
    path('<int:id>/', views.tournament_retrieve, name='retrieve'),
    path('<int:id>/delete/', views.tournament_delete, name='delete'),
    path('<int:id>/participants/<int:participant_id>',
         views.tournament_participant_delete,
         name='delete-participant'),

    path('<int:id>/group_stage/start/', stage_views.tournament_group_stage_start, name='group-stage-start'),
    path('<int:id>/group_stage/results/', stage_views.tournament_group_stage_result, name='group-stage-result'),

    path('<int:id>/stage/start/', stage_views.tournament_playoff_start, name='playoff-start'),
    path('<int:id>/stage/results/', stage_views.tournament_playoff_result, name='playoff-result'),

    path('', views.tournament_list, name='list'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('apps.core.urls', namespace='core')),
    path('tournaments/<int:tournament_id>/teams/', include('apps.teams.urls', namespace='teams')),
    path('tournaments/', include('apps.tournaments.urls', namespace='tournaments')),
    path('admin/', admin.site.urls),
]

apps/tournaments/models.py
from django.db import models

from random import randint
from ..core.models import RandomNameGeneratedModel, TimeStampModel
from ..core import ADJECTIVES, NOUNS, TournamentStages
from . import Divisions


class Tournament(RandomNameGeneratedModel, TimeStampModel):

    is_active = models.BooleanField(default=True, blank=True)
    current_stage = models.CharField(
        max_length=20,
        choices=TournamentStages.choices,
        default=TournamentStages.PREPARATION,
        db_index=True,)

    def change_stage(self, new_stage):
        self.current_stage = new_stage
        self.save(update_fields=('current_stage',))

    def generate_name(self):
        adjective = ADJECTIVES[randint(0, len(ADJECTIVES)-1)]
        noun = NOUNS[randint(0, len(NOUNS)-1)]
        return f"{adjective.upper()} {noun.upper()} TOURNAMENT"

    class Meta:
        verbose_name = "Tournament"
        verbose_name_plural = "Tournament"


class TournamentParticipant(models.Model):

    @property
    def points(self):
        games_as_left_player = self.as_left_player.all()
        points = sum(game.left_player_score for game in games_as_left_player)

        games_as_right_player = self.as_right_player.all()
        points += sum(game.right_player_score for game in games_as_right_player)
        # TODO: Count points and staff
        return points

    tournament = models.ForeignKey(
        'tournaments.Tournament',
        related_name='participants',
        on_delete=models.CASCADE
    )

    team = models.ForeignKey(
        'teams.Team',
        related_name='participantions',
        on_delete=models.CASCADE
    )

    in_game = models.BooleanField(default=True)
    division = models.CharField(
        max_length=20,
        choices=Divisions.choices,
        default=Divisions.NOT_ASSIGNED,
    )


    class Meta:
        verbose_name = "Tournament participant"
        verbose_name_plural = "Tournament participants"

apps/tournaments/forms.py
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Layout, Submit
from django import forms
from .models import Tournament


class TournamentCreateForm(forms.ModelForm):

    class Meta:
        model = Tournament
        fields = ('name', )

apps/tournaments/views.py
from django.shortcuts import render

from .forms import TournamentCreateForm
from .models import Tournament, TournamentParticipant


def tournament_list(request, *args, **kwargs):
    tournaments = Tournament.objects.all()
    new_tournament = None
    if request.method == "POST":
        form = kwargs.get('form', None)
        if form is not None:
            new_tournament = form.instance

    deleted_tournament = kwargs.get('deleted_tournament', None)

    for tournament in tournaments:
        tournament.fields = dict(
            (
                field.name,
                field.value_to_string(tournament)
            ) for field in tournament._meta.fields
        )

    return render(request, 'tournaments/tournaments_list.html', {
        'new_tournament': new_tournament,
        'deleted_tournament': deleted_tournament,
        'tournaments': tournaments,
    })


def tournament_create(request, *args, **kwargs):

    if request.method == "POST":
        form = TournamentCreateForm(request.POST)
        if form.is_valid():
            form.save()
            return tournament_list(request, form=form)

    form = TournamentCreateForm()

    return render(request, 'tournaments/tournaments_create.html',
                  {'form': form})


def tournament_delete(request, id):
    try:
        instance = Tournament.objects.get(id=id)
        instance.delete()
    except Tournament.DoesNotExist as e:
        return render(request, 'core/404.html')

    return tournament_list(request, deleted_tournament=instance)


def tournament_retrieve(request, id, **kwargs):

    new_participant = None
    if request.method == "POST":
        new_participant = kwargs.get('new_participant', None)

    deleted_participant = kwargs.get('deleted_participant', None)

    try:
        instance = Tournament.objects.get(id=id)
    except Tournament.DoesNotExist as e:
        return render(request, 'core/404.html')

    participants = instance.participants.all()
    participants = sorted(participants, key=lambda m: m.points, reverse=True)

    return render(request, 'tournaments/tournaments_retrieve.html', {
        'tournament': instance,
        'participants': participants,
        'participants_count': len(participants),
        'new_participant': new_participant,
        'deleted_participant': deleted_participant,
    })


def tournament_participant_delete(request, id, participant_id):

    try:
        instance = TournamentParticipant.objects.get(id=participant_id)
        instance = instance.delete()
    except Tournament.DoesNotExist as e:
        return render(request, 'core/404.html')

    return tournament_retrieve(request, id, deleted_participant=instance)

apps/tournaments/templates/tournaments/tournaments_create.html
{% extends 'core/base.html' %}
{#{% extends '' %}#}
{% load crispy_forms_tags %}

{% block title %}Tournament creation {% endblock title %}

{% block content %}
    <h1 class="display-6">Create tournament:</h1>
{#        {% crispy form form.helper %}#}
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <span class="badge badge-warning">* Leave blank to automatically assign name to tournament.</span>
        <br>
        <button type="submit" class="btn btn-primary" style="margin-top: 10px">Create</button>
    </form>
{% endblock content %}

apps/tournaments/templates/tournaments/tournaments_group_stage.html
{% extends 'core/base.html' %}
{#{% extends '' %}#}

{% block title %} Tournament Group Stage {% endblock title %}

{% block content %}

    <h1 class="display-6">Tournament Group Stage:</h1>

    <h3 class="display-6">Tournament:</h3>
    <h6> Id : {{ tournament.id }}</h6>
    <h6> Name : {{ tournament.name }}</h6>
    <h6> Stage : {{ tournament.current_stage }}</h6>

    <table class="table table-striped table-bordered table-hover" style="display: inline; float: left">

        <caption>List of participants in 1st division</caption>
        <thead class="thead-dark">
            <tr>
                <th>Num.</th>
                <th>Name</th>
                <th>Division</th>
                <th>Points</th>
            </tr>
        </thead>
        {% for participant in first_division_participants %}
            <tr>

                <td>{{ forloop.counter  }}</td>
                <td><a href="{% url 'teams:retrieve' tournament_id=tournament.id id=participant.team.id %}">{{ participant.team.name }}</a></td>
                <td>{{ participant.division }}</td>
                <td>{{ participant.points }}</td>
            </tr>
        {% endfor %}
    </table>

    <table class="table table-striped table-bordered table-hover" style="display: inline; float: right;">

        <caption>List of participants in 2nd division</caption>
        <thead class="thead-dark">
          <tr>
              <th>Num.</th>
              <th>Name</th>
              <th>Division</th>
              <th>Points</th>
          </tr>
        </thead>
        {% for  participant in second_division_participants %}
            <tr>

                <td>{{ forloop.counter  }}</td>
                <td><a href="{% url 'teams:retrieve' tournament_id=tournament.id id=participant.team.id %}">{{ participant.team.name }}</a></td>
                <td>{{ participant.division }}</td>
                <td>{{ participant.points }}</td>
            </tr>
        {% endfor %}
    </table>


    <form action="{% url 'tournaments:group-stage-result'  id=tournament.id%}">
        <input type="submit" class="btn btn-success" value="Start the Group Stage" />
    </form>

{% endblock content %}

apps/tournaments/templates/tournaments/tournaments_group_stage_results.html
{% extends 'core/base.html' %}
{#{% extends '' %}#}

{% block title %} Tournament Group Stage {% endblock title %}

{% block content %}

    <h1 class="display-6">Tournament Group Stage Results:</h1>

    <h3 class="display-6">Tournament:</h3>
    <h6> Id : {{ tournament.id }}</h6>
    <h6> Name : {{ tournament.name }}</h6>
    <h6> Stage : {{ tournament.current_stage }}</h6>


    <h3 class="display-6" style="text-align: center">First Division Results:</h3>
    <table class="table table-striped table-bordered table-hover" style="display: inline; float: left">

        <thead class="thead-dark">
            <tr>
                <th></th>
                {% for participant in first_division_participants %}
                    {% if participant.in_game %}
                        <th scope="col">{{ participant.team.name }}</th>
                    {% else %}
                        <th scope="col" style="background: #6a6f73; color:#45484d">{{ participant.team.name }} (eliminated)</th>
                    {%  endif %}
                {% endfor %}
            </tr>
        </thead>
            {% for result_row in first_division_matrix %}
                <tr>
                    {% if result_row.participant_in_game %}
                        <th class="dark" scope="row" style="background: #31373e; color:white">{{ result_row.participant_name }}</th>
                    {% else %}
                        <th scope="col" style="background: #6a6f73; color:#45484d">{{ result_row.participant_name }} (eliminated)</th>
                    {%  endif %}

                    {% for result_cell in result_row.games %}

                        {% if result_cell.self %}
                            <td class="dark" style="background: #31373e"></td>
                        {% else %}
                            <td>
                                {{ result_cell.left_score }}
                                {{ result_cell.right_score }}
                                {{ result_cell.winner }}
                            </td>
                        {% endif %}
                    {% endfor %}
                </tr>
            {% endfor %}
    </table>

    <h3 class="display-6" style="text-align: center">Second Division Results:</h3>
     <table class="table table-striped table-bordered table-hover" style="display: inline; float: left">

        <thead class="thead-dark">
            <tr>
                <th></th>
                {% for participant in second_division_participants %}
                    {% if participant.in_game %}
                        <th scope="col">{{ participant.team.name }}</th>
                    {% else %}
                        <th scope="col" style="background: #6a6f73; color:#45484d">{{ participant.team.name }} (eliminated)</th>
                    {%  endif %}
                {% endfor %}
            </tr>
        </thead>
            {% for result_row in second_division_matrix %}
                <tr>
                    {% if result_row.participant_in_game %}
                        <th class="dark" scope="row" style="background: #31373e; color:white">{{ result_row.participant_name }}</th>
                    {% else %}
                        <th scope="col" style="background: #6a6f73; color:#45484d">{{ result_row.participant_name }} (eliminated)</th>
                    {%  endif %}

                    {% for result_cell in result_row.games %}

                        {% if result_cell.self %}
                            <td class="dark" style="background: #31373e"></td>
                        {% else %}
                            <td>
                                {{ result_cell.left_score }}
                                {{ result_cell.right_score }}
                                {{ result_cell.winner }}
                            </td>
                        {% endif %}
                    {% endfor %}
                </tr>
            {% endfor %}
    </table>

    <form action="{% url 'tournaments:playoff-start' id=tournament.id%}">
        <input type="submit" class="btn btn-success" value="Start the Play Off Stage" />
    </form>

{% endblock content %}

apps/tournaments/templates/tournaments/tournaments_list.html
{% extends 'core/base.html' %}
{#{% extends '' %}#}

{% block title %} Tournament listing {% endblock title %}

{% block content %}
    {% if new_tournament %}
        <div class="alert alert-success" role="alert">
            New tournament <strong>{{ new_tournament.name }}</strong> has been successfully created!
        </div>
    {% endif %}

    {% if deleted_tournament %}
        <div class="alert alert-warning" role="alert">
            Tournament <strong>{{ deleted_tournament.name }}</strong> has been deleted!
        </div>
    {% endif %}

    <h1 class="display-6">Table of tournaments:</h1>
    <table class="table table-striped table-bordered table-hover">

        <caption>List of tournaments</caption>
        <thead class="thead-dark">
          <tr>
            <th>Num.</th>
            <th>Name</th>
            <th>Stage</th>
            <th>Is Active</th>
            <th></th>
          </tr>
        </thead>
        {% for tournament in tournaments %}
            <tr>

                    <td>{{ forloop.counter }}</td>
                    <td><a href="{% url 'tournaments:retrieve' id=tournament.id %}">{{ tournament.name }}</a></td>
                    <td>{{ tournament.current_stage }}</td>
                    <td>{{ tournament.is_active }}</td>
                    <td>
                    <form action="{% url 'tournaments:delete' id=tournament.id %}">
                        <input type="submit" class="btn btn-danger" value="Delete" />
                    </form>
                    </td>
            </tr>

        {% endfor %}
    </table>

    <form action="{% url 'tournaments:create'%}">
        <input type="submit" class="btn btn-primary" value="Create New Tournament" />
    </form>

{% endblock content %}

{#<!DOCTYPE html>#}
{#<html lang="en">#}
{#<head>#}
{#  <meta charset="UTF-8">#}
{#  <meta name="viewport" content="width=device-width, initial-scale=1.0">#}
{#  <meta http-equiv="X-UA-Compatible" content="ie=edge">#}
{##}
{#  <title>Default title</title>#}
{#  <title>{% block title %}{% endblock title %}</title>#}
{#  <link rel="stylesheet" href="{% static 'styles.css' %}">#}
{#</head>#}
{#<body>#}
{#    {% for name in names %}#}
{#        <h1>This is tournaments list! {{ name }}</h1>#}
{#        <a href="{% url 'tournaments:retrieve' id=1 %}">Leads to datail motail</a>#}
{#    {% endfor %}#}
{#</body>#}
{#</html>#}

apps/tournaments/templates/tournaments/tournaments_playoff_stage.html
{% extends 'core/base.html' %}
{#{% extends '' %}#}

{% block title %} Tournament Group Stage {% endblock title %}

{% block content %}

    <h1 class="display-6">Playoff Games:</h1>

    <h3 class="display-6">Tournament:</h3>
    <h6> Id : {{ tournament.id }}</h6>
    <h6> Name : {{ tournament.name }}</h6>
    <h6> Current Stage : {{ tournament.current_stage }}</h6>

    <table class="table table-striped table-bordered table-hover">
        <thead class="thead-dark">
            <tr>
                <th>Num.</th>
                <th>Right player</th>
                <th>Left player</th>
                <th>Stage</th>
                <th>Right player Score</th>
                <th>Left player Score</th>
                <th>Winner</th>
            </tr>
        </thead>
        {% for game in games %}
            <tr>

                <td>{{ forloop.counter }}</td>
                <td>{{ game.right_player.team.name }}</td>
                <td>{{ game.left_player.team.name }}</td>
                <td>{{ game.stage }}</td>
                <td>{{ game.right_player_score }}</td>
                <td>{{ game.left_player_score }}</td>
                <td>{{ game.winner }}</td>
            </tr>

        {% endfor %}
    </table>


    <form action="{% url 'tournaments:playoff-result' id=tournament.id%}">
        <input type="submit" class="btn btn-success" value="Start the Play Off Stage" />
    </form>

{% endblock content %}

apps/tournaments/templates/tournaments/tournaments_playoff_stage_results.html
{% extends 'core/base.html' %}
{#{% extends '' %}#}

{% block title %} Tournament Group Stage {% endblock title %}

{% block content %}

    <h1 class="display-6">Playoff Games:</h1>

    <h3 class="display-6">Tournament:</h3>
    <h6> Id : {{ tournament.id }}</h6>
    <h6> Name : {{ tournament.name }}</h6>
    <h6> Current Stage : {{ tournament.current_stage }}</h6>

    <table class="table table-striped table-bordered table-hover">
        <thead class="thead-dark">
            <tr>
                <th>Num.</th>
                <th>Right player</th>
                <th>Left player</th>
                <th>Stage</th>
                <th>Right player Score</th>
                <th>Left player Score</th>
                <th>Winner</th>
            </tr>
        </thead>
        {% for game in games %}
            <tr>

                <td>{{ forloop.counter }}</td>
                <td>
                    {{ game.right_player.team.name }}
                    {% if game.right_player.in_game %}
                        Passed
                    {% else %}
                        Eliminated
                    {% endif %}
                </td>
                <td>{{ game.left_player.team.name }}

                    {% if game.left_player.in_game %}
                        Passed
                    {% else %}
                        Eliminated
                    {% endif %}
                </td>
                <td>{{ game.stage }}</td>
                <td>{{ game.right_player_score }}</td>
                <td>{{ game.left_player_score }}</td>
                <td>{{ game.winner }}</td>
            </tr>

        {% endfor %}
    </table>


    <form action="{% url 'tournaments:playoff-start' id=tournament.id%}">
        <input type="submit" class="btn btn-success" value="Start the Play Off Stage" />
    </form>

{% endblock content %}

apps/tournaments/templates/tournaments/tournaments_retrieve.html
{% extends 'core/base.html' %}
{#{% extends '' %}#}

{% block title %} Tournament datailing {% endblock title %}

{% block content %}

    {% if new_participant %}
        <div class="alert alert-success" role="alert">
            New tournament <strong>{{ new_participant.team.name }}</strong> has been successfully created!
        </div>
    {% endif %}

    {% if deleted_participant %}
        <div class="alert alert-warning" role="alert">
            Tournament <strong>{{ deleted_participant.team.name }}</strong> has been deleted!
        </div>
    {% endif %}

    <h1 class="display-6">Tournament Information:</h1>
    <h6> Id : {{ tournament.id }}</h6>
    <h6> Name : {{ tournament.name }}</h6>
    <h6> Stage : {{ tournament.current_stage }}</h6>

    <h1 class="display-6">Table of participants:</h1>
        <table class="table table-striped table-bordered table-hover">
        <caption>List of participants</caption>
        <thead class="thead-dark">
            <tr>
              <th>Num.</th>
              <th>Name</th>
              <th>Points</th>
              <th>Division</th>
              <th></th>
            </tr>
        </thead>
        {% for participant in participants %}
            <tr>
                <td>{{ forloop.counter  }}</td>
                <td><a href="{% url 'teams:retrieve' tournament_id=tournament.id id=participant.team.id %}">{{ participant.team.name }}</a></td>
                <td>{{ participant.points }}</td>
                <td>{{ participant.division }}</td>
                <td>
                    {% if tournament.current_stage == "PREPARATION" %}
                        <form action="{% url 'tournaments:delete-participant' participant_id=participant.id id=tournament.id %}">
                            <input type="submit" class="btn btn-danger" value="Delete" />
                        </form>
                    {% else %}
                        <form action="{% url 'tournaments:delete-participant' participant_id=participant.id id=tournament.id %}">
                            <input type="submit" class="btn btn-danger disabled" value="Delete" disabled/>
                        </form>
                    {% endif %}
                </td>
            </tr>
        {% endfor %}
        </table>

        {% if participants_count < 16 %}
            <form action="{% url 'teams:create' tournament_id=tournament.id %}">
                <div class="form-group">
                    <input type="submit" class="btn btn-primary" value="Add New Team" />
                </div>
            </form>

           <form action="{% url 'teams:auto-create' tournament_id=tournament.id%}">
                <div class="form-group">
                    <input type="submit" class="btn btn-primary" value="Generate Teams Randomly" />
                </div>
           </form>

        {% else %}
            <form action="{% url 'teams:create' tournament_id=tournament.id %}">
                <div class="form-group">
                    <input type="submit" class="btn btn-primary disabled " value="Add New Team" disabled/>
                </div>
            </form>

            <form class="form-inline" action="{% url 'teams:auto-create' tournament_id=tournament.id %}">
                <div class="form-group">
                    <input type="submit" class="btn btn-primary disabled " value="Generate Teams Randomly" disabled/>
                </div>
            </form>
            <br/>
        {% endif %}

        {% if tournament.is_active == False %}
            <span class="badge badge-warning">Tournament is over.</span>
        {% elif participants_count == 16 %}
            <form action="{% url 'tournaments:group-stage-start' id=tournament.id%}">
                <input type="submit" class="btn btn-success" value="Start tournament" />
            </form>
        {% elif  participants_count < 16  %}
            <span class="badge badge-warning">You have not got sufficient number of teams to start the tournament. Add some more. (It's required to be 8 teams)</span>
        {% else %}
            <span class="badge badge-warning">You have too many teams to start tournament. Remove some of them. (It's required to be 8 teams)</span>
        {% endif %}

{% endblock content %}

apps/tournaments/templates/tournaments/tournaments_winner.html
{% extends 'core/base.html' %}
{% load static %}
{#{% extends '' %}#}
{% block header_content %}

    <style>
        @import url(https://fonts.googleapis.com/css?family=Sigmar+One);

        body {
            background: #3da1d1;
            color: #fff;
            overflow: hidden;
        }

        .congrats {
            position: absolute;
            top: 140px;
            width: 550px;
            height: 100px;
            padding: 20px 10px;
            text-align: center;
            margin: 0 auto;
            left: 0;
            right: 0;
        }

        h1 {
            transform-origin: 50% 50%;
            font-size: 50px;
            font-family: 'Sigmar One', cursive;
            cursor: pointer;
            z-index: 2;
            position: absolute;
            top: 0;
            text-align: center;
            width: 100%;
        }

        .blob {
            height: 50px;
            width: 50px;
            color: #ffcc00;
            position: absolute;
            top: 45%;
            left: 45%;
            z-index: 1;
            font-size: 30px;
            display: none;
        }
    </style>
{% endblock header_content %}
{% block title %} Tournament listing {% endblock title %}

{% block content %}
    <div class="congrats">
        <h1>WINNER OF {{ tournament.name }} IS {{ participant.team.name }}!</h1>
    </div>
    <img src="https://bit.ly/20qKWK0" style="display:none">



    <form action="{% url 'tournaments:list'%}">
        <input type="submit" class="btn btn-warning" style="color: white; font-weight: bold" value="Back To Tournaments" />
    </form>

{% endblock content %}